// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfxiukoltisqvcgfvirg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmeGl1a29sdGlzcXZjZ2Z2aXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODM0NDEsImV4cCI6MjA2NTA1OTQ0MX0.o0VGxZK7FraEZCvGMLFkakoXO4e43OuYQbR-5W0Biuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);